# Site settings
title: HS Hackers NYC
location: New York City
description: "Welcome to the High School Hackers NYC meetup group!"
baseurl: ""
url: "http://authenticjazzweekend.github.io/nyc"

# More settings
accent: "#E74C3C"
twitter: "hshackersnyc"
github: "hshackers/nyc"
contact: "hello at victorlourng dot com"
organizers: "John Mormon and Jon Moss"

# Get Meetup Notifications, visible or hidden
notifications: "visible"

# Get Meetup Notifications, IFTTT recipie URLs
email: "https://ifttt.com/recipes/186850-hs-hackers-nyc-e-mail-notifications"
gcal: "https://ifttt.com/recipes/186851-google-calendar-for-hs-hackers-nyc"
sms: ""
android: ""
ifttt: "http://ifttt.com/"

# Local Meetup Links
meetup1: "The Young Hackers"
meetup1-url: "http://younghackers.us/"
meetup2: "NYC TechBreakfast"
meetup2-url: "http://www.meetup.com/NYC-TechBreakfast/"
meetup3: "NY Tech Meetup"
meetup3-url: "http://www.meetup.com/ny-tech/"

# Build settings
markdown: kramdown
permalink: pretty

prose:
  rooturl: '_posts'
  siteurl: 'http://authenticjazzweekend.github.io/nyc'
  media: 'media'
  ignore:
    - index.html
    - meetups.html
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      meetups:
        - name: "meetup"
          field:
            element: "hidden"
            value: "meetup"
        - name: "categories"
          field: 
            element: "hidden"
            value: "meetup"
        - name: "permalink"
          field:
            element: "text"
            label: "Permalink"
            value: ""
        - name: "date"
          field:
            element: "text"
            label: "Date (YYYY-MM-DD HH:MM:SS)"
            value: "2014-06-08 10:30:00"
        - name: "host"
          field:
            element: "text"
            label: "Host"
            value: ""
        - name: "address"
          field:
            element: "text"
            label: "Address"
            value: ""
        - name: "link"
          field:
            element: "text"
            label: "Link"
            value: ""
        - name: "background"
          field:
            element: "text"
            label: "Background (CSS)"
            value: "url() #03152A"
